### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by Yysheepsheep** [TSY845/UFLDv2_MobileNetV3#1]
Hello, I would like to ask if there has been a decrease in the parameter count of the UFLDv2 model after replacing the backbone with moblivenetv3 compared to resnet1

**Comment by Yysheepsheep** [comment]
UFLDv2

**Comment by TSY845** [comment]
Yes. The original ResNet-18 has around 11M params, and the ResNet-34 has more than 20M params. However, according to the MobileNetV3 paper, even the biggest V3-Large model has only around 5M parameters. So there is a significant decrease in parameter amount.

**Comment by Yysheepsheep** [comment]
Ok, thanks for your reply, I also want to achieve lightweighting by replacing the backbone. Finally, moblivenetv3 is the parameter data obtained after your experiment? Have you replaced other networks, or can you recommend some other lightweight networks for me? Thank you

**Comment by TSY845** [comment]
The MobileNetV3 author provides the parameter data I referred to in their paper. Since I did not change the MobileNetV3 architecture, I think the number should be correct. Unfortunately, I did not try out other lightweight networks due to limited time. But you can try to implement them as long as you make sure the input dimension, output dimension, and downsampling rate match the original architecture.

**Comment by Yysheepsheep** [comment]
Hello, I encountered this issue while implementing Mobile netv3. Could you please help me answer it
![image](https://github.com/TSY845/UFLDv2_MobileNetV3/assets/115567314/92ab2db8-d75b-4314-96de-f5804bc3ea84)

**Comment by Yysheepsheep** [comment]
Hello, I would like to ask where the specific settings for the input and output dimensions of the Mobilenetv3 model in the code you provided are?

**Comment by TSY845** [comment]
> provided

Check backbone.py and layer.py in the model folder
